

import "./globals.css";
import "./styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";


// Prime react
import "primereact/resources/themes/saga-blue/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";

// Components
import Header from "@/components/layout/landing/header";
import ReceiveNotification from "@/components/dashboard/messages/receive-notification";
import Footer from "@/components/layout/Footer";
import ReactQueryProvider from "./ReactQueryProvider";
import { ToastContainer } from "react-toastify";
import InitialDispatch from "@/components/initialDispatch";
import { UserContextProvider } from "@/store/userContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mutivendor",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <UserContextProvider>
          <body className={`${inter.className} bg-gray-100`}>
            <ToastContainer />
            <ReceiveNotification />
            <InitialDispatch>
              <Header />
              <main className="min-h-[100vh] md:min-h-[90vh]">{children}</main>
              <Footer />
            </InitialDispatch>
          </body>
        </UserContextProvider>
      </ReactQueryProvider>
    </html>
  );
}
